name: Deploy CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: npm install
      - run: npm test -- main.spec.ts
      - run: npm run build
        env:
          CI: true
      - run: npm test -- build.spec.ts
      - run: touch ./dist/simple-timeout/.npmignore
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: "./dist/shipthisapi-js/package.json"
